-- =============================================================================
-- canonical_facts_full_reload.sql
-- Truncates all tables and reinserts the complete authoritative dataset.
-- Run ONCE against data/canonical_facts.db:
--
--   sqlite3 data/canonical_facts.db < canonical_facts_full_reload.sql
--
-- Corrections applied vs. prior data:
--   characters id=1   occupation: "Research Scientist" → "PhD Candidate"
--   characters id=3   is_alive: 1 → 0  (Emma Hartwell died Dec 2020)
--   characters id=7   occupation: "Investment Banker" → "AGM, The Loyalist"
--   timeline_events id=1  description/location: wrong "tech mixer" → correct parking lot/Colectivo
--   character_negatives id=3  explanation: "celiac disease" → "non-celiac gluten sensitivity"
--   schedules id=6    location/start_time: Lakefront → Skokie, 06:00 → 06:20
--   possessions id=12  name: "Turing" → "Pinstripe"; description corrected to F56
--   possessions id=13  description: "2021 Mini Cooper S" → "2019 Volvo XC40 R-Design"
-- =============================================================================

PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;

-- =============================================================================
-- TRUNCATE (children before parents)
-- =============================================================================
DELETE FROM event_participants;
DELETE FROM relationships;
DELETE FROM possessions;
DELETE FROM schedules;
DELETE FROM character_negatives;
DELETE FROM education;
DELETE FROM location_rooms;
DELETE FROM timeline_events;
DELETE FROM update_log;
DELETE FROM ingestion_metadata;
DELETE FROM last_run_state;
DELETE FROM characters;
DELETE FROM locations;

-- Reset autoincrement counters
UPDATE sqlite_sequence SET seq = 0 WHERE name IN (
    'characters','locations','location_rooms','timeline_events',
    'event_participants','relationships','possessions','schedules',
    'character_negatives','education','update_log','ingestion_metadata'
);


-- =============================================================================
-- LOCATIONS  (21 rows: 15 existing + 6 new)
-- =============================================================================
INSERT INTO locations
    (id,name,address_street,address_city,address_state,address_zip,
     location_type,building_type,floor_count,unit_number,square_feet,
     owner_id,ownership_type,monthly_cost,purchase_date,
     neighborhood,distance_to_chicago_loop,nearby_landmarks,is_fictional,
     created_at,updated_at,source_file)
VALUES
-- existing
(1,'Paul''s House','9636 N Kostner Ave','Skokie','IL','60076',
 'residence','Mid-century brick home',2,NULL,NULL,
 2,'owned',NULL,NULL,
 'Skokie',NULL,'["Skokie Swift CTA station","I-94 Edens Expressway","Old Orchard Shopping Center"]',0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(2,'Hartwell Estate','Sheridan Road','Kenilworth','IL',NULL,
 'residential_single_family',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(3,'Caroline Hartwell-Montgomery House',NULL,'Glencoe','IL',NULL,
 'residential_single_family',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(4,'Alice & Steve Thomas House',NULL,'Wilmette','IL',NULL,
 'residential_single_family',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(5,'DDB Chicago Office',NULL,'Chicago','IL',NULL,
 'commercial_office',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(6,'Danny O''Brien House',NULL,'Chicago','IL',NULL,
 'residential_single_family',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(7,'Sean O''Brien House',NULL,'Chicago','IL',NULL,
 'residential_single_family',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(8,'Marie Brennan House',NULL,'Oak Park','IL',NULL,
 'residential_single_family',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(9,'Loyola University Chicago','1032 W Sheridan Rd','Chicago','IL',NULL,
 'educational_university',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(10,'New Trier High School','385 Winnetka Ave','Winnetka','IL',NULL,
 'educational_high_school',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(11,'Niles North High School','9800 Lawler Ave','Skokie','IL',NULL,
 'educational_high_school',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(12,'Illinois State Water Survey','2204 Griffith Dr','Champaign','IL',NULL,
 'research_facility',NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(13,'Kate''s Apartment','Hinman Avenue','Evanston','IL','60201',
 'residence','1-bedroom apartment, 750 sq ft, third-floor walkup in 1960s brick building',1,NULL,NULL,
 NULL,'rented',NULL,NULL,
 'Near Central Street/Downtown Evanston',NULL,'["Northwestern campus (0.9 miles)","Lake Michigan","downtown Evanston"]',0,
 '2026-01-24 16:05:37','2026-01-24 16:05:37',NULL),
(14,'Linda''s House',NULL,'Naperville','IL',NULL,
 'residence','Family home where Kate and Mike grew up. Linda lives alone here since divorce (2001).',NULL,NULL,NULL,
 NULL,'owned',NULL,NULL,
 'Naperville suburb',NULL,NULL,0,
 '2026-01-24 16:05:37','2026-01-24 16:05:37',NULL),
(15,'Argonne National Laboratory','9700 S Cass Ave','Lemont','IL','60439',
 'research_facility','U.S. Department of Energy national laboratory. Priya works in Materials Science Division.',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,0,
 '2026-01-24 16:05:37','2026-01-24 16:05:37',NULL),
-- new
(16,'4612 N. Glenwood Ave','4612 N. Glenwood Ave','Chicago','IL','60640',
 'residential_multi_family','Vintage courtyard apartment building, 3-story brick U-shaped, built ~1924, 18 units',3,NULL,NULL,
 NULL,'rented',NULL,NULL,
 'Ravenswood','~9 miles north','["Brown Line Damen stop (~0.5mi)","Lawrence Ave corridor","Swedish Hospital (~1.5mi)"]',0,
 datetime('now'),datetime('now'),NULL),
(17,'Evan Mercer Apartment (2R)','4612 N. Glenwood Ave','Chicago','IL','60640',
 'residence','One-bedroom, second floor, rear-facing unit in 1920s courtyard building',1,'2R',550,
 NULL,'rented',1350.0,NULL,
 'Ravenswood','~9 miles north','["4612 N. Glenwood building","Brown Line Damen stop"]',0,
 datetime('now'),datetime('now'),NULL),
(18,'Megan Lindqvist Apartment (3F)','4612 N. Glenwood Ave','Chicago','IL','60640',
 'residence','Two-bedroom, third floor, front-facing unit in 1920s courtyard building',1,'3F',950,
 NULL,'rented',1700.0,NULL,
 'Ravenswood','~9 miles north','["4612 N. Glenwood building","courtyard-facing windows","Brown Line Damen stop"]',0,
 datetime('now'),datetime('now'),NULL),
(19,'Threshold Water Inc.','220 N Green Street','Chicago','IL','60607',
 'commercial_office','Dedicated ~3,500 sq ft office suite within Workbox co-working building (renovated industrial)',1,NULL,3500,
 NULL,'rented',NULL,NULL,
 'West Loop / Fulton Market','~2 miles west','["Workbox co-working","Google Chicago nearby","Fulton Market District","Blue Line"]',0,
 datetime('now'),datetime('now'),NULL),
(20,'Swedish Hospital (Endeavor Health)','5145 N. California Ave','Chicago','IL','60625',
 'medical_facility','Community hospital, NorthShore/Endeavor Health system, founded 1886 by Swedish immigrants',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 'North Park','~10 miles north','["Peterson Park","Megan''s workplace","Nora born here","Lindqvist family historical connection"]',0,
 datetime('now'),datetime('now'),NULL),
(21,'Karl & Birgit Lindqvist House','4848 N. Hermitage Ave','Chicago','IL','60640',
 'residence','Brick two-flat; first floor owner-occupied, second floor rented to Petersons. Karl''s grandfather bought 1932.',2,'First floor',NULL,
 NULL,'owned',NULL,NULL,
 'Ravenswood','~9 miles north','["Six blocks from Evan/Megan''s building","Ravenswood Covenant Church nearby"]',0,
 datetime('now'),datetime('now'),NULL);


-- =============================================================================
-- CHARACTERS  (66 rows: 48 existing + 18 new)
-- Corrections: id=1 occupation, id=3 is_alive, id=7 occupation
-- =============================================================================
INSERT INTO characters
    (id,full_name,preferred_name,age,birthday,birth_year,
     height_inches,weight_lbs,build,hair_color,hair_length,eye_color,
     distinctive_features,occupation,employer,job_title,
     work_location,work_schedule_type,phone,email,
     residence_id,character_type,is_alive,created_at,updated_at,source_file)
VALUES
-- ── PRIMARY ──────────────────────────────────────────────────────────────────
(1,'Katherine Marie Morrison','Kate',32,'1993-03-15',NULL,
 66,128,'slim','blonde','shoulder-length','green',
 '["shoulder-length hair","runner build","engaging smile"]',
 'PhD Candidate, Environmental Engineering','Northwestern University','PhD Candidate',  -- CORRECTED
 NULL,NULL,NULL,NULL,
 NULL,'primary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(2,'Paul Rogala','Paul',34,'1990-07-12',NULL,
 70,NULL,'average','dark brown',NULL,'brown',
 '["tech professional appearance","Mini Cooper enthusiast","small white scar near eyebrow (childhood accident)"]',
 'Software Engineering Manager','Red River','Engineering Manager',
 NULL,NULL,NULL,NULL,
 1,'primary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
-- ── SECONDARY ────────────────────────────────────────────────────────────────
(3,'Emma Hartwell','Emma',28,'1997-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Former teacher, deceased 2020',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',0,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),  -- CORRECTED is_alive
(4,'Patrick O''Brien','Patrick',60,'1965-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Chicago Fire Department Captain (retired)',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(5,'Maureen Murphy O''Brien','Maureen',58,'1967-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Elementary school teacher (Oak Park)',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(6,'Ashley O''Brien','Ashley',28,'1997-11-15',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Account Executive at marketing agency',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(7,'Marcus Chen','Marcus',36,'1989-06-20',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Assistant General Manager, The Loyalist','Loyalist','Front of House Manager',  -- CORRECTED
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(8,'Alice Thomas','Alice',31,'1994-03-08',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Account Director at DDB Chicago',NULL,NULL,
 NULL,NULL,NULL,NULL,
 4,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(9,'Mike Morrison','Mike',29,'1996-07-12',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Marketing Manager at TechFlow Solutions',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
-- ── SUPPORTING ───────────────────────────────────────────────────────────────
(10,'Charles Harrison Hartwell III','Charles',62,'1963-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Managing Partner, corporate litigation law firm',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(11,'Victoria Lancaster Hartwell','Victoria',59,'1966-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Philanthropist, charity board member',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(12,'Caroline Victoria Hartwell-Montgomery','Caroline',31,'1994-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Homemaker, Junior League, charity boards',NULL,NULL,
 NULL,NULL,NULL,NULL,
 3,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(13,'Stratton Montgomery III','Stratton',33,'1992-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Investment banker',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(14,'Daniel Francis O''Brien','Danny',63,'1962-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Retired CPD Sergeant',NULL,NULL,
 NULL,NULL,NULL,NULL,
 6,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(15,'Joan Murphy O''Brien','Joan',62,'1963-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Retired elementary school principal',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(16,'Sean Michael O''Brien','Sean',56,'1969-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Union carpenter, Local 1 Chicago',NULL,NULL,
 NULL,NULL,NULL,NULL,
 7,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(17,'Maria Gonzalez O''Brien','Maria',54,'1971-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Dental hygienist',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'supporting',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(40,'Steve Thomas','Steve',34,'1991-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Business professional (client-facing, travels extensively)',NULL,NULL,
 NULL,NULL,NULL,NULL,
 4,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(44,'Linda Marie Morrison','Linda',61,'1964-04-22',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 14,'secondary',1,'2026-01-24 16:04:57','2026-01-24 16:04:57',NULL),
(45,'Priya Anjali Mehta','Priya',28,'1997-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-24 16:04:57','2026-01-24 16:04:57',NULL),
(46,'Rajesh Patel','Raj',30,'1995-01-01',NULL,
 70,NULL,'lean','black','short','brown',
 '["calm demeanor","good listener"]',
 'Software Engineer','Trading Firm','Software Engineer',
 NULL,NULL,NULL,NULL,
 NULL,'supporting',1,'2026-01-24 16:05:22','2026-01-24 16:05:22',NULL),
(31,'Dr. Patricia Chen','Patricia Chen',46,'1979-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Associate Professor, Civil & Environmental Engineering, Northwestern',NULL,NULL,
 NULL,NULL,NULL,NULL,
 NULL,'secondary',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
-- ── MINOR ────────────────────────────────────────────────────────────────────
(18,'Meghan O''Brien Callahan','Meghan',38,'1987-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'High school English teacher',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(19,'Daniel O''Brien Jr.','DJ',35,'1990-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Chicago firefighter',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(20,'Kevin O''Brien','Kevin',32,'1993-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Accountant',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(21,'Erin O''Brien','Erin',29,'1996-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Nurse at Northwestern Memorial',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(22,'Patrick O''Brien Jr.','Patrick Jr.',31,'1994-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Electrician',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(23,'Grace O''Brien Martinez','Grace',28,'1997-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Social worker at DCFS',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(24,'Michael O''Brien','Mikey',25,'2000-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Medical student, Loyola Stritch (3rd year)',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(25,'Ana O''Brien','Ana',22,'2003-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Marketing (entry-level)',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(26,'Marie Catherine Murphy Brennan','Marie',55,'1970-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Nurse Practitioner at Oak Park clinic',NULL,NULL,NULL,NULL,NULL,NULL,
 8,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(27,'James Brennan','James',57,'1968-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'High school history teacher at Oak Park-River Forest HS',NULL,NULL,NULL,NULL,NULL,NULL,
 8,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(28,'Sarah Brennan','Sarah',29,'1996-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Elementary school teacher',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(29,'Thomas Brennan','Tom',27,'1998-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Software engineer',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(30,'Katie Brennan','Katie',24,'2001-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Social worker (starting career)',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(32,'Dr. Michael Brennan','Michael Brennan',58,'1967-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Professor, Civil & Environmental Engineering, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(33,'Dr. Sarah Kline','Sarah Kline',37,'1988-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Associate Professor, Chemistry, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(34,'Dr. James Rodriguez','James Rodriguez',41,'1984-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Associate Professor, Civil & Environmental Engineering, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(35,'Dr. Lisa Wu','Lisa Wu',55,'1970-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Senior Research Scientist, Illinois State Water Survey',NULL,NULL,NULL,NULL,NULL,NULL,
 12,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(36,'Dr. David Chen','David Chen',32,'1993-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Postdoctoral Researcher, Chen Lab, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(37,'Jessica Okonkwo','Jessica',28,'1997-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'PhD student (Year 6), Chen Lab, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(38,'Rashid Ahmed','Rashid',25,'2000-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'PhD student (Year 1), Chen Lab, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(39,'Sarah Goldstein','Sarah Goldstein',38,'1987-01-01',NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Marketing executive',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(41,'Ms. Rodriguez','Ms. Rodriguez',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'High school teacher (Kate''s time)',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(42,'Ahmad','Ahmad',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'PhD student (Year 5), Environmental Engineering, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(43,'Diane','Diane',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Administrative Coordinator, Environmental Engineering Dept, Northwestern',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-16 03:07:48','2026-01-16 03:07:48',NULL),
(47,'Neha Mehta','Neha',25,'2000-01-01',NULL,
 NULL,NULL,NULL,'black',NULL,'brown',NULL,
 'Medical Student','Rutgers Robert Wood Johnson Medical School',NULL,NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-24 16:05:22','2026-01-24 16:05:22',NULL),
(48,'Professor Sarah Chen','Prof. Sarah Chen',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Professor','Northwestern University','Professor, Materials Science and Engineering',NULL,NULL,NULL,NULL,
 NULL,'minor',1,'2026-01-24 16:05:22','2026-01-24 16:05:22',NULL),
-- ── NEW PRIMARY (Evan project) ────────────────────────────────────────────────
(49,'Evan Mercer','Evan',28,'1997-03-15',1997,
 72,175,'lean, wiry; distance-runner build; broader through shoulders',
 'dark brown','short (military-close)','blue',
 '["small scar on left forearm (training accident)","Navy frogman silhouette tattoo on left ribcage (3 inches, below heart)","looks older than 28 (sun/sleep deprivation aged him)","slightly asymmetric gait due to reconstructed left knee"]',
 'Software Engineer','Threshold Water Inc.','Software Engineer',
 'Hybrid (remote + Threshold Water office, 220 N Green St Chicago)','full_time',NULL,NULL,
 17,'primary',1,datetime('now'),datetime('now'),NULL),
(50,'Megan Lindqvist','Megan',24,'2001-08-03',2001,
 66,NULL,'fit; functional nurse build (on feet 12 hrs/shift)',
 'blonde','medium-length (ponytail or bun for work, down on days off)','light blue',
 '["Lindqvist eyes — light blue, same as Karl","fair skin","freckles across nose and cheeks (visible summer, fade winter)","looks younger than 24","warm and quiet manner"]',
 'Registered Nurse, Oncology','Swedish Hospital (Endeavor Health)','RN, Oncology Unit',
 'Swedish Hospital, 5145 N. California Ave, Chicago','shift_work_12hr',NULL,NULL,
 18,'primary',1,datetime('now'),datetime('now'),NULL),
-- ── NEW MINOR (Evan project) ──────────────────────────────────────────────────
(51,'Nora Lindqvist','Nora',1,'2025-01-18',2025,
 NULL,NULL,NULL,'blonde (baby-fine wisps)',NULL,'brown',
 '["two bottom teeth, two top coming in (Feb 2026)","walks unsteadily","says mama and nana"]',
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 18,'minor',1,datetime('now'),datetime('now'),NULL),
(52,'Karl Lindqvist','Karl',67,'1958-02-11',1958,
 NULL,NULL,NULL,NULL,NULL,'light blue',
 '["Lindqvist eyes","bilateral rotator cuff damage (left surgically repaired 2019, right managed conservatively)","chronic lower back pain from 40 years electrical work"]',
 'Retired Electrician (IBEW Local 134)','Retired',NULL,NULL,'retired',NULL,NULL,
 21,'secondary',1,datetime('now'),datetime('now'),NULL),
(53,'Birgit Lindqvist','Birgit',65,'1960-09-14',1960,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["warm but restrained Scandinavian affect","Type 2 diabetes (diet-controlled + metformin)","mild hypertension (well-controlled)"]',
 'Retired School Secretary','Retired (formerly Ravenswood Elementary CPS)',NULL,NULL,'retired',NULL,NULL,
 21,'secondary',1,datetime('now'),datetime('now'),NULL),
(54,'Erik Lindqvist','Erik',30,NULL,1995,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["Megan''s older brother","direct opinions, less restrained than Karl"]',
 'Electrician','IBEW Local 134',NULL,NULL,NULL,NULL,NULL,
 NULL,'supporting',1,datetime('now'),datetime('now'),NULL),
(55,'Ryan Callahan','Ryan',27,NULL,1998,
 NULL,NULL,NULL,'dark',NULL,NULL,
 '["handsome in conventional sense","charming","father absent/estranged from Nora since Aug 2025"]',
 'Business professional',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'supporting',1,datetime('now'),datetime('now'),NULL),
-- ── NEW THRESHOLD WATER TEAM ──────────────────────────────────────────────────
(56,'Samir Rajesh Patel','Samir',37,'1989-05-15',1989,
 NULL,NULL,'average, runner''s physique',NULL,NULL,NULL,
 '["CEO co-founder","MIT PhD","driven by Dearborn/Flint water crisis exposure (Thanksgiving 2015)"]',
 'CEO & Co-Founder, Threshold Water Inc.','Threshold Water Inc.','CEO & Co-Founder',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'secondary',1,datetime('now'),datetime('now'),NULL),
(57,'Vikram Desai','Vikram',42,'1984-03-08',1984,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["CTO co-founder","rebuilt platform from scratch 2024","systems architecture expertise","born Mumbai, immigrated age 3"]',
 'CTO & Co-Founder, Threshold Water Inc.','Threshold Water Inc.','CTO & Co-Founder',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'secondary',1,datetime('now'),datetime('now'),NULL),
(58,'Sophia Park','Sophia',29,NULL,1996,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Lead Backend Engineer','Threshold Water Inc.','Lead Backend Engineer',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'supporting',1,datetime('now'),datetime('now'),NULL),
(59,'Eric Tran','Eric',26,NULL,1999,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["engaged to Anna Zielinska","marrying April 17 2026","promoted Senior Engineer Oct 2026"]',
 'Full-Stack Engineer','Threshold Water Inc.','Full-Stack Engineer',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'supporting',1,datetime('now'),datetime('now'),NULL),
(60,'Daniel Wu','Daniel',27,NULL,1998,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["junior data scientist","Kate will mentor him from March 2026"]',
 'Data Scientist','Threshold Water Inc.','Data Scientist',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'supporting',1,datetime('now'),datetime('now'),NULL),
(61,'Carmen Silva','Carmen',32,NULL,1993,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Product Manager','Threshold Water Inc.','Product Manager',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'supporting',1,datetime('now'),datetime('now'),NULL),
(62,'Hannah Berg','Hannah',31,NULL,1994,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["wife of Josh Berg"]',
 'Customer Success Manager','Threshold Water Inc.','Customer Success Manager',
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'supporting',1,datetime('now'),datetime('now'),NULL),
(63,'Anna Zielinska','Anna',25,NULL,2000,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["accepted Malcolm X dental hygiene program Jun 2026","marrying Eric Tran April 17 2026","works cafe while completing prereqs"]',
 'Cafe Worker / Dental Hygiene Student (starting Jun 2026)',NULL,NULL,NULL,NULL,NULL,NULL,
 NULL,'supporting',1,datetime('now'),datetime('now'),NULL),
(64,'Kyle Dunning','Kyle',30,NULL,1995,
 NULL,NULL,'built like a fire hydrant',NULL,NULL,NULL,
 '["Evan''s closest friend from SEAL Teams","breacher from North Carolina","lives Virginia Beach","same EVE Online corporation as Evan (OSBL-V)"]',
 'Unknown (veteran)',NULL,NULL,'Virginia Beach, VA',NULL,NULL,NULL,
 NULL,'supporting',1,datetime('now'),datetime('now'),NULL),
(65,'Dana Jefferson','Dana',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,
 '["Megan''s friend","pediatrics nurse at Glenbrook Hospital"]',
 'Registered Nurse, Pediatrics','Glenbrook Hospital','RN, Pediatrics',
 'Glenbrook Hospital','full_time',NULL,NULL,
 NULL,'supporting',1,datetime('now'),datetime('now'),NULL),
(66,'Marco Reyes','Marco',NULL,NULL,NULL,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'Unknown','Threshold Water Inc.',NULL,
 '220 N Green Street, Chicago IL 60607','full_time',NULL,NULL,
 19,'minor',1,datetime('now'),datetime('now'),NULL);


-- =============================================================================
-- LOCATION ROOMS  (27 rows: 14 existing + 13 new)
-- =============================================================================
INSERT INTO location_rooms
    (id,location_id,room_name,floor_level,room_type,
     width_feet,length_feet,width_inches,length_inches,
     current_use,key_features,furniture,adjacent_to,
     has_exterior_window,window_direction,source_file)
VALUES
-- existing (Paul's house, location_id=1)
(1,1,'Entry & Foyer','Main Floor','entry',4.0,14.0,4.0,8.0,
 'Entry foyer',
 '["covered front entry","long narrow space","stair run to lower level"]',
 '["console table","coat storage"]',
 NULL,0,NULL,NULL),
(2,1,'Living Room','Main Floor','living',14.0,14.0,11.0,8.0,
 'Living room',
 '["curved bay window","excellent natural light","near-square proportions"]',
 '["sofa","chairs","32-inch TV","sound bar","media furniture","hutch"]',
 NULL,0,NULL,NULL),
(3,1,'Dining Room','Main Floor','dining',8.0,11.0,0.0,4.0,
 'Dining room',
 '["connector between living room and kitchen"]',
 '["6-person dining table"]',
 NULL,0,NULL,NULL),
(4,1,'Kitchen','Main Floor','kitchen',10.0,10.0,6.0,10.0,
 'Kitchen',
 '["compact but efficient","side door to patio","supports serious cooking"]',
 '["U-shaped counters","cabinets"]',
 NULL,0,NULL,NULL),
(5,1,'Primary Bedroom','Main Floor','bedroom',14.0,10.0,2.0,11.0,
 'Primary bedroom',
 '["away from living areas","true retreat positioning"]',
 '["queen bed","nightstands","dressers"]',
 NULL,0,NULL,NULL),
(6,1,'Bedroom 2','Main Floor','bedroom',11.0,11.0,1.0,3.0,
 'Guest bedroom',
 '["notably square","usable space"]',
 '["guest bed","furniture"]',
 NULL,0,NULL,NULL),
(7,1,'Bedroom 3','Main Floor','office',11.0,11.0,1.0,3.0,
 'Home office',
 '["Paul''s primary workspace","notably square","professional setup"]',
 '["desk","two 32-inch monitors on arms","multiple computers","filing cabinet"]',
 NULL,0,NULL,NULL),
(8,1,'Full Bath #1','Main Floor','bathroom',7.0,5.0,3.0,2.0,
 'Full bathroom',
 '["serves bedrooms and guests"]',
 '["tub/shower","toilet","sink"]',
 NULL,0,NULL,NULL),
(9,1,'Full Bath #2','Main Floor','bathroom',7.0,4.0,3.0,10.0,
 'Full bathroom',
 '["dual-bath configuration","allows simultaneous use"]',
 '["bathtub","sink","toilet"]',
 NULL,0,NULL,NULL),
(10,1,'Recreation Room','Lower Level','recreation',31.0,17.0,11.0,5.0,
 'Media and entertainment',
 '["exceptionally large","standout feature","long open footprint","can be zoned"]',
 '["large TV","sofas","surround sound","bookcases"]',
 NULL,0,NULL,NULL),
(11,1,'Lower-Level Bedroom','Lower Level','bedroom',11.0,15.0,7.0,9.0,
 'Guest bedroom / Kate''s workspace',
 '["exceeds many main-level bedrooms","private home office potential"]',
 '["bed","desk area"]',
 NULL,0,NULL,NULL),
(12,1,'Lower-Level Bathroom','Lower Level','bathroom',6.0,7.0,5.0,3.0,
 'Full bathroom',
 '["enables independent use of lower level"]',
 '["full bath fixtures"]',
 NULL,0,NULL,NULL),
(13,1,'Laundry Room','Lower Level','utility',19.0,10.0,0.0,0.0,
 'Laundry and utility',
 '["unusually large","rare and valuable","feels like workroom not closet"]',
 '["full-size washer","dryer","folding stations","storage cabinets","utility sink"]',
 NULL,0,NULL,NULL),
(14,1,'Mechanical Room','Lower Level','utility',10.0,9.0,4.0,3.0,
 'Mechanical systems',
 '["cleanly separated","doesn''t intrude on living space"]',
 '["HVAC","water heater"]',
 NULL,0,NULL,NULL),
-- new: Evan's Apt 2R (location_id=17)
(15,17,'Living Room','2','living',NULL,NULL,NULL,NULL,
 'Only common space; one rear-facing window',
 '["original single-pane glass (cold to touch in winter)","steam radiator beneath window (no modulation)"]',
 '["IKEA desk","monitor/keyboard/mouse setup","small couch"]',
 NULL,1,'alley/west','glenwood-building-complete.md'),
(16,17,'Kitchen','2','kitchen',NULL,NULL,NULL,NULL,
 'Minimal galley kitchen',
 '["appliances from mid-2000s era","limited counter space"]',
 '["single pan","single pot","coffee maker"]',
 'Living Room',1,NULL,'glenwood-building-complete.md'),
(17,17,'Bedroom','2','bedroom',NULL,NULL,NULL,NULL,
 'Primary bedroom; pull-up bar in doorway',
 '["pull-up bar bolted in doorway","rear-facing window (original single-pane)"]',
 '["mattress on metal frame","framed platoon photo on desk"]',
 NULL,1,'alley/rear','glenwood-building-complete.md'),
(18,17,'Bathroom','2','bathroom',NULL,NULL,NULL,NULL,
 'Full bath',
 '["white subway tile walls","gray hex floor tile","pedestal sink with hairline crack near drain (pre-existing)","claw-foot tub/shower reglazed","recessed medicine cabinet","low water pressure (second floor)"]',
 '["pedestal sink","claw-foot tub with shower","toilet"]',
 'Bedroom/hallway',0,NULL,'glenwood-building-complete.md'),
-- new: Megan's Apt 3F (location_id=18)
(19,18,'Living/Dining Room','3','living',NULL,NULL,NULL,NULL,
 'Combined living-dining; afternoon light best in building',
 '["9-ft original plaster ceilings","hardwood floors (refinished)","two courtyard-facing double-hung windows","cast-iron radiator beneath left window","double-pane glass (2003 renovation)"]',
 '["IKEA Friheten sleeper sofa (gray)","IKEA rug (beige, machine-washable)","Nora''s toy basket (corner)","photos on fridge"]',
 NULL,1,'south/courtyard','glenwood-building-complete.md'),
(20,18,'Kitchen','3','kitchen',NULL,NULL,NULL,NULL,
 'Galley; renovated ~2019-2020; best-renovated space in unit',
 '["stainless gas range (30-inch, 4 sealed burners)","dishwasher","counter-depth refrigerator","light gray laminate countertop","subway tile backsplash","small courtyard-facing window above sink"]',
 '["gas range","dishwasher","refrigerator"]',
 'Living/Dining Room',1,'courtyard','glenwood-building-complete.md'),
(21,18,'Megan''s Bedroom','3','bedroom',NULL,NULL,NULL,NULL,
 'Larger bedroom; faces Glenwood Ave; best natural light',
 '["east-facing primary window","secondary courtyard-adjacent window (only bedroom in either apt with 2 windows)","double closet (two full-width sliding doors)","cast-iron radiator on exterior wall"]',
 '["queen mattress on metal frame","dresser","nightstand with lamp and phone charger"]',
 NULL,1,'east (street)','glenwood-building-complete.md'),
(22,18,'Nora''s Room','3','bedroom',NULL,NULL,NULL,NULL,
 'Smaller bedroom; quieter; courtyard-facing nursery',
 '["one double-hung courtyard-facing window","reach-in closet (single door)","cast-iron radiator on courtyard wall"]',
 '["crib (Birgit bought)","small dresser for baby clothes","glider chair (Birgit insisted)","blackout curtains","white noise machine","shelf with board books"]',
 NULL,1,'courtyard','glenwood-building-complete.md'),
(23,18,'Bathroom','3','bathroom',NULL,NULL,NULL,NULL,
 'One bathroom; vintage tile; dripping faucet',
 '["black and white hexagonal tile","tub with shower attachment","dripping faucet (reported to Kowalski twice)"]',
 '["tub/shower","toilet","sink"]',
 NULL,0,NULL,'glenwood-building-complete.md'),
-- new: Threshold Water office (location_id=19)
(24,19,'Open Office','1','office',NULL,NULL,NULL,NULL,
 'Main working area; desks for all team members',
 '["exposed brick","high ceilings (renovated industrial)","standing desks"]',
 '["standing desks","ergonomic chairs","multiple monitors per desk"]',
 NULL,1,NULL,'threshold-water-snapshot-feb-2026.md'),
(25,19,'Conference Room','1','meeting',NULL,NULL,NULL,NULL,
 'Team meetings, investor calls, customer demos',
 '["whiteboard wall","video conferencing setup"]',
 '["conference table","chairs","display screen"]',
 'Open office',1,NULL,'threshold-water-snapshot-feb-2026.md'),
(26,19,'Small Kitchen / Break Area','1','utility',NULL,NULL,NULL,NULL,
 'Shared break area',
 '["coffee setup","mini fridge","counter seating"]',
 '["coffee maker","mini fridge","counter stools"]',
 'Open office',0,NULL,'threshold-water-snapshot-feb-2026.md'),
(27,19,'Storage Closet','1','utility',NULL,NULL,NULL,NULL,
 'Server equipment and water sample equipment storage',
 '["server hardware","water testing equipment"]',
 '["server racks","sample containers"]',
 'Open office',0,NULL,'threshold-water-snapshot-feb-2026.md');


-- =============================================================================
-- TIMELINE EVENTS  (44 rows: 18 existing + 26 new)
-- Correction: id=1 description and location
-- =============================================================================
INSERT INTO timeline_events
    (id,event_date,event_date_precision,event_title,event_description,
     location_id,location_description,event_category,significance,is_canonical,source_file)
VALUES
-- existing (id=1 corrected)
(1,'2025-09-06','day','Kate and Paul First Meeting',
 'Kate Morrison and Paul Rogala meet spontaneously in the Sherman Avenue parking lot in Evanston. Kate''s key fob battery is dying; Paul offers to help. They walk to CVS together, buy a CR2032 battery, Paul shows Kate how to replace it. Kate invites Paul for coffee at Colectivo Coffee (716 Church St, corner Church & Sherman). 70-minute conversation (3:00-4:15 PM). They discover a shared gluten sensitivity. Paul asks to meet again; Kate agrees. Meeting catalyst: both driving Mini Coopers.',
 NULL,'Sherman Ave parking lot → CVS → Colectivo Coffee (716 Church St, Evanston IL)',
 'relationship',NULL,1,'scene-archive-index.md'),
(2,'2024-04-21','day','Kate comprehensive exam',
 'Kate passed comprehensive exam. Three-hour oral defense. Committee of five grilled her. Patricia toughest questioner. Major milestone — now ABD.',
 NULL,NULL,NULL,'high',1,NULL),
(3,'2025-10-15','day','Kate proposal defense',
 'Kate defended detailed research plan for remaining PhD years. Committee approved with minor revisions.',
 NULL,NULL,NULL,'high',1,NULL),
(4,'2023-12-13','day','Kate AGU 2023 poster',
 'Kate''s first major conference. Poster presentation on microplastics and PFAS in Chicago drinking water. San Francisco, Moscone Center. Overwhelmed by scale (20,000+ attendees). Skipped AGU student mixer.',
 NULL,NULL,NULL,'medium',1,NULL),
(5,'2024-04-09','day','Kate Illinois Water Conference',
 'Kate presented at regional conference at UIUC (her undergrad). Connected with Dr. Lisa Wu who later joined committee. Strange being back at undergrad campus.',
 NULL,NULL,NULL,'medium',1,NULL),
(6,'2024-11-18','day','Kate SETAC oral presentation',
 'Kate''s first major oral at national conference. Portland, OR. Very nervous but presented clearly. Tough Q&A, handled well. Skipped conference banquet and EPA mixer.',
 NULL,NULL,NULL,'medium',1,NULL),
(7,'2015-10-01','day','Ashley O''Brien family dinner',
 'Emma met O''Brien family. Patrick: "So you''re the friend Ashley won''t shut up about." Emma unused to warmth, volume, casual affection.',
 NULL,NULL,NULL,'low',1,NULL),
(8,'2016-03-15','day','Emma O''Brien spring break',
 'Emma joined O''Brien family vacation to Gulf Shores. First family vacation she actually enjoyed. Cried on last night.',
 NULL,NULL,NULL,'low',1,NULL),
(9,'2016-01-15','day','Alice and Steve meet',
 'Alice met Steve at bar near UIUC campus. He was Northwestern MBA student visiting friends. Started dating casually.',
 NULL,NULL,NULL,'medium',1,NULL),
(10,'2017-12-15','day','Alice and Steve engaged',
 'Romantic proposal in Chicago with Christmas lights.',
 NULL,NULL,NULL,'medium',1,NULL),
(11,'2018-06-15','day','Alice and Steve wedding',
 'Elegant wedding, 150 people. Beautiful day.',
 NULL,NULL,NULL,'high',1,NULL),
(12,'2020-10-15','day','Alice and Steve move to Wilmette',
 'Moved from Chicago to Wilmette. Needed more space with two kids. Better schools.',
 4,NULL,NULL,'medium',1,NULL),
(13,'2025-09-26','day','Kate and Paul first dinner date & first kiss',
 'First actual dinner date, 3 weeks after meeting. Tapas Barcelona, Davis Street, Evanston. Kate drove herself. Shared tapas — patatas bravas, gambas al ajillo, champiñones, pimientos de padrón. Natural conversation, Kate laughs genuinely. Paul walks Kate to her car. Paul asks permission for first kiss — brief, gentle, reads her nervousness perfectly. Kiss in parking lot on Davis Street (~8:25 PM). Kate drives home processing everything.',
 NULL,'Tapas Barcelona, Davis Street, Evanston IL',
 'relationship','high',1,'kate-morrison-important-dates-2025.md'),
(14,'2025-10-17','day','First overnight at Kate''s apartment',
 'Kate invited Paul to her apartment for first time (6 weeks into relationship). Kate made dinner. First overnight stay together. Physical intimacy progressing (not full sex yet). Trust beginning to form.',
 13,'Kate''s apartment, Evanston',
 'relationship','high',1,'kate-morrison-important-dates-2025.md'),
(15,'2025-11-23','day','First hockey game & first time having sex',
 'Kate''s first live hockey game. Blackhawks vs. Avalanche at United Center (1-0 shutout loss). Kate told Paul childhood Zamboni story during intermission. Later that evening at Paul''s house: first time having sex (11 weeks into relationship). Trust fully established at physical level.',
 1,'United Center, then Paul''s house Skokie',
 'relationship','high',1,'kate-paul-blackhawks-game-november-23-2025.md'),
(16,'2025-12-06','day','Kate meets Marcus Chen',
 'Kate met Marcus Chen (Paul''s best friend) at Paul''s house. Watching Blackhawks game together. First friend integration milestone. Marcus cautiously evaluating Kate (protective of Paul after Christie). Marcus''s assessment: "She seems nice" (cautious approval).',
 1,'Paul''s house, Skokie',
 'relationship','high',1,'kate-paul-marcus-blackhawks-december-6-2025.md'),
(17,'2025-12-27','day','Kate and Paul say "I love you"',
 'Afternoon: Ashley lunch, told Emma''s story and "six years or sixty years" philosophy. Evening at Paul''s house: Kate processed Ashley''s story with Paul, then said "I love you" first. Paul said it back. 16 weeks into relationship. Trust fully established at emotional level.',
 1,'Paul''s house, Skokie',
 'relationship','high',1,'kate-morrison-paul-evening-december-27-2025.md'),
(18,'2025-12-28','day','Kate and Paul become official boyfriend/girlfriend',
 'Following "I love you" exchange, Kate and Paul discussed and agreed they are officially boyfriend/girlfriend. Relationship status formalized.',
 1,'Paul''s house, Skokie',
 'relationship','high',1,'kate-morrison-sunday-morning-december-28-complete.md'),
-- new Kate/Paul arc
(19,'2025-12-30','day','Key Exchange — Paul gives Kate a key to his house',
 'Paul gives Kate a key to his Skokie house. Literal and metaphorical threshold. Kate keeps it on her key ring from this point. Same day: Colectivo Coffee meeting with Priya — Kate tells Priya about staying.',
 1,'Paul''s house, Skokie IL',
 'relationship','high',1,'scene-archive-index.md'),
(20,'2026-01-01','day','New Year together',
 'Kate and Paul spend New Year''s Eve and New Year''s Day together at Paul''s house. First week of de facto cohabitation complete.',
 1,'Paul''s house, Skokie IL',
 'relationship','medium',1,'scene-archive-index.md'),
(21,'2026-01-09','day','Kate meets Alice Thomas — Lou Malnati''s dinner',
 'Paul hosts dinner at Lou Malnati''s (Lincolnwood original location, opened St. Patrick''s Day 1971) with his sister Alice Thomas and husband Steve. Kate meets Paul''s sister for the first time. Alice had PPD crisis 2019; Paul was her primary support. Alice cautiously evaluating Kate. Went well.',
 NULL,'Lou Malnati''s, Lincolnwood IL',
 'relationship','high',1,'scene-archive-index.md'),
(22,'2026-01-11','day','Paul meets Linda Morrison',
 'Paul meets Kate''s mother Linda Morrison for the first time. Linda loving but anxious and overwhelming. Paul handles it well.',
 14,'Linda''s house, Naperville IL',
 'relationship','high',1,'scene-archive-index.md'),
(23,'2026-01-13','day','Kate gives notice on Evanston apartment',
 'Kate contacts her landlord and gives 30-day notice to vacate. Move-out date: February 15, 2026. Three years and four months in the Evanston apartment ends. No backup plan. Committed to cohabitation without exit strategy.',
 13,'Kate''s Evanston apartment',
 'cohabitation','high',1,'kate-apartment-building-incident-january-2026.md'),
(24,'2026-01-17','day','Kate meets Paul''s parents',
 'Kate meets Paul''s parents for the first time. Family integration complete on Paul''s side.',
 NULL,'Rogala family home',
 'relationship','high',1,'scene-archive-index.md'),
(25,'2026-01-19','day','Kate''s workspace established at Paul''s house',
 'Kate''s home office set up in the lower-level bedroom at Paul''s house. Desk, external monitor, proper workspace for dissertation writing. The lower bedroom is now Kate''s primary work space.',
 1,'Paul''s house — lower-level bedroom, Skokie IL',
 'cohabitation','medium',1,'scene-archive-index.md'),
(26,'2026-01-22','day','Samir Patel emails Kate about Threshold Water opportunity',
 'Samir Rajesh Patel (CEO, Threshold Water) emails Kate. Found her through publications and Northwestern network. Proposes part-time research scientist / data consultant role. Kate initially skeptical. Reads email multiple times.',
 NULL,'Email (remote)',
 'career','high',1,'scene-2026-01-22-samir-email-narrative.md'),
(27,'2026-01-24','day','Samir calls Kate — Threshold Water phone conversation',
 'Phone call between Samir and Kate. Kate has reviewed Threshold''s platform and done background research. Samir outlines role: part-time, $55/hr, fully remote, data audit + predictive model improvement. Kate agrees to in-person meeting.',
 NULL,'Phone (remote)',
 'career','high',1,'scene-2026-01-24-saturday-samir-call-apartment-narrative.md'),
(28,'2026-02-03','day','Kate meets Vikram Desai — technical deep dive',
 'Kate meets Vikram Desai (CTO, Threshold Water) for technical deep-dive. Vikram reviews Kate''s publication and current data audit approach. Kate''s environmental engineering background maps directly onto Threshold''s sensor data and contamination prediction work. Vikram satisfied with technical fit.',
 19,'Threshold Water office, 220 N Green Street, Chicago IL',
 'career','high',1,'scene-2026-02-03-tuesday-vikram-meeting-narrative.md'),
(29,'2026-02-09','day','Kate visits Threshold Water office',
 'Kate''s in-person office visit to Threshold Water. Evaluating the opportunity and the team. Meets Carmen Silva and other team members. Sees the workspace.',
 19,'Threshold Water office, 220 N Green Street, Chicago IL',
 'career','medium',1,'kate-morrison-threshold-water-complete-timeline.md'),
(30,'2026-02-15','day','Kate officially moves out of Evanston apartment',
 'Kate''s Evanston apartment lease ends. Three years and four months at the Hinman Avenue apartment ends. All belongings consolidated at Paul''s Skokie house. "His house" becomes "our house." Full cohabitation with no backup apartment.',
 13,'Kate''s former Evanston apartment → Paul''s house Skokie',
 'cohabitation','high',1,'scene-archive-index.md'),
(31,'2026-02-20','day','Kate accepts Threshold Water offer',
 'Kate Morrison formally accepts Threshold Water part-time position. $55/hr, ~10-15 hrs/week to start, fully remote with occasional in-person. Start date: March 1, 2026. First industry work since AECOM (2015-2018). Career pivot to hybrid academic-industry model.',
 NULL,'Remote (Paul''s house, Skokie)',
 'career','high',1,'kate-morrison-threshold-water-complete-timeline.md'),
(32,'2026-03-01','day','Kate starts at Threshold Water — first day',
 'Kate Morrison begins part-time role at Threshold Water Inc. Data audit phase: reviewing existing sensor data, identifying gaps, assessing current predictive model baselines. 10-15 hrs/week. Mentoring relationship with Daniel Wu begins.',
 NULL,'Remote (Paul''s house, Skokie)',
 'career','high',1,'kate-morrison-2026-complete-timeline.md'),
(33,'2026-06-13','day','Mike Morrison and Ashley O''Brien Wedding',
 'Mike Morrison and Ashley O''Brien marry in Chicago. Saturday. Kate takes week off from Threshold Water (June 7-14). Kate is maid of honor. Paul attends as Kate''s partner.',
 NULL,'Chicago IL (venue TBD)',
 'family','high',1,'kate-morrison-2026-complete-timeline.md'),
-- new Evan arc
(34,'2024-10-01','month','Evan Mercer moves to Chicago',
 'Evan moves to Chicago from Virginia Beach for a software engineering role at a government-adjacent SaaS firm (secure workflow platforms for federal clients). Found through veteran hiring pipeline. Starting salary $85K. Found apartment at 4612 N. Glenwood Ave (Apt 2R, $1,350/mo) on Craigslist. Knows nobody in the city. Drove his 2018 gray Tacoma from Virginia Beach with everything he owned.',
 17,'4612 N. Glenwood Ave, Apt 2R, Ravenswood, Chicago',
 'life','high',1,'evan-mercer-complete-background.md'),
(35,'2026-01-01','month','Evan Mercer laid off',
 'Evan''s employer (government-adjacent federal SaaS firm) lays him off. Manager Phil: "This isn''t performance. This is contract math." Financially stable — savings, investments, no debt — but enforced pause is its own difficulty for a man built for action.',
 17,'4612 N. Glenwood Ave, Apt 2R',
 'career','high',1,'evan-mercer-complete-background.md'),
(36,'2026-02-16','day','Evan — Veridian Systems recruiter screen',
 'Monday. Phone screen with Veridian Systems recruiter. One of 67+ applications. Lukewarm but advances to technical round.',
 NULL,'Remote (apartment, Ravenswood)',
 'career','medium',1,'evan-mercer-handoff-feb16-19-2026.md'),
(37,'2026-02-18','day','Evan receives Threshold Water scheduling email',
 'Wednesday. Threshold Water sends scheduling email for technical interview. One of 67+ applications. Telemetry ingestion, infrastructure monitoring, water systems — maps to Evan''s federal SaaS and SATCOM planning background. No premonitory weight. Just another recruiter email.',
 NULL,'Remote (apartment, Ravenswood)',
 'career','medium',1,'scene-2026-02-18-wednesday-evan-narrative.md'),
(38,'2026-02-20','day','Evan — Veridian Systems Round 1 technical interview',
 'Friday. Veridian technical interview. Lukewarm — Evan''s systems-level thinking does not fit their frontend-heavy stack. Advances but without enthusiasm from either side.',
 NULL,'Remote',
 'career','low',1,'scene-2026-02-20-friday-evan-narrative.md'),
(39,'2026-02-23','day','Evan — Threshold Water technical interview (Vikram Desai)',
 'Monday. Technical interview with Vikram Desai (CTO). Vikram recognizes Evan''s incident response instincts and systems-level thinking immediately. The SATCOM planning maps to infrastructure debugging under pressure. Evan''s calm registers clearly. Strong mutual fit.',
 NULL,'Remote',
 'career','high',1,'scene-2026-02-23-monday-evan-vikram-narrative.md'),
(40,'2026-02-24','day','Evan receives and accepts Threshold Water offer',
 'Tuesday. Threshold Water extends offer: Software Engineer, $115K. Evan accepts same day. Start date: March 2, 2026. Calls Kyle Dunning in Virginia Beach. Tells Kyle over EVE Online comms that evening while running a wormhole site.',
 NULL,'Remote (apartment, Ravenswood)',
 'career','high',1,'scene-2026-02-24-tuesday-evan-offer-day-narrative.md'),
-- new Megan arc
(41,'2026-02-11','day','Megan signs lease at 4612 N. Glenwood Ave',
 'Megan signs lease with Mr. Kowalski for Apt 3F. $1,700/month. Mr. Kowalski remembered the Lindqvist name — Karl did electrical work on the building in the early 2000s. Connection did not get a discount but got a lease without hassle and early move-in.',
 18,'Apt 3F, 4612 N. Glenwood Ave, Ravenswood',
 'life','high',1,'scene-2026-02-11-wednesday-megan-lease-narrative.md'),
(42,'2026-02-28','day','Megan Lindqvist moves into 4612 N. Glenwood (Apt 3F)',
 'Saturday. Megan''s official move-in day. Karl and Erik arrive 8 AM with Erik''s F-150. Birgit stays at Hermitage house with Nora. Move is small — Megan left Ryan''s furniture behind; everything is from the Lindqvist house or flat-pack IKEA. Three flights, no elevator, cold February morning. Evan is in the courtyard between tasks and notices the move-in sounds. First encounter between Evan and Megan/the Lindqvist family.',
 16,'4612 N. Glenwood Ave courtyard → Apt 3F',
 'life','high',1,'scene-2026-02-28-saturday-evan-narrative.md'),
-- canonical anchor
(43,'2026-03-02','day','Evan Mercer first day at Threshold Water',
 'Monday. Evan starts at Threshold Water Inc., 220 N Green Street, Chicago IL 60607. First day in the office. Meets the team: Samir, Vikram, Sophia Park, Eric Tran, Daniel Wu, Carmen Silva, Hannah Berg. First full-time job in Chicago. Canonical anchor point for both the Evan project and the Kate Morrison project.',
 19,'Threshold Water office, 220 N Green Street, Chicago IL 60607',
 'career','high',1,'scene-archive-index.md'),
-- Anna/Eric
(44,'2026-04-17','day','Eric Tran and Anna Zielinska courthouse wedding',
 'Eric and Anna marry at the courthouse. Both families present. Dinner at Beacon St after. Moving into second floor of Anna''s parents'' two-flat at 4623 N. Beacon in late May, after Tomasz renovates the unit (wedding gift). Eric promoted to Senior Engineer October 2026.',
 NULL,'Cook County Courthouse, Chicago IL',
 'relationship','medium',1,'anna-eric-2026-complete-timeline.md');


-- =============================================================================
-- EVENT PARTICIPANTS  (61 rows: 2 existing + 59 new)
-- =============================================================================
INSERT INTO event_participants (id,event_id,character_id,role) VALUES
-- existing
(1,1,1,'participant'),
(2,1,2,'participant'),
-- events 13-18 (Kate/Paul relationship milestones)
(3,13,1,'participant'),
(4,13,2,'participant'),
(5,14,1,'participant'),
(6,14,2,'participant'),
(7,15,1,'participant'),
(8,15,2,'participant'),
(9,16,1,'participant'),
(10,16,2,'participant'),
(11,16,7,'participant'),
(12,17,1,'participant'),
(13,17,2,'participant'),
(14,18,1,'participant'),
(15,18,2,'participant'),
-- event 19: key exchange
(16,19,1,'recipient'),
(17,19,2,'giver'),
-- event 20: new year
(18,20,1,'participant'),
(19,20,2,'participant'),
-- event 21: meets Alice
(20,21,1,'participant'),
(21,21,2,'host'),
(22,21,8,'participant'),
(23,21,40,'participant'),
-- event 22: Paul meets Linda
(24,22,1,'participant'),
(25,22,2,'participant'),
(26,22,44,'participant'),
-- event 23: apartment notice
(27,23,1,'participant'),
-- event 24: meets Paul's parents
(28,24,1,'participant'),
(29,24,2,'participant'),
-- event 25: workspace
(30,25,1,'participant'),
(31,25,2,'participant'),
-- event 26: Samir email
(32,26,1,'recipient'),
(33,26,56,'sender'),
-- event 27: Samir call
(34,27,1,'participant'),
(35,27,56,'participant'),
-- event 28: Vikram meeting
(36,28,1,'participant'),
(37,28,57,'participant'),
-- event 29: office visit
(38,29,1,'participant'),
(39,29,56,'participant'),
-- event 30: moves out
(40,30,1,'participant'),
(41,30,2,'participant'),
-- event 31: accepts offer
(42,31,1,'participant'),
-- event 32: starts Threshold
(43,32,1,'participant'),
(44,32,60,'mentee'),
-- event 33: wedding
(45,33,9,'groom'),
(46,33,6,'bride'),
(47,33,1,'maid_of_honor'),
(48,33,2,'guest'),
(49,33,44,'guest'),
-- event 34: Evan moves to Chicago
(50,34,49,'participant'),
-- event 35: Evan laid off
(51,35,49,'participant'),
-- event 36: Veridian screen
(52,36,49,'participant'),
-- event 37: Threshold scheduling email
(53,37,49,'recipient'),
(54,37,56,'sender'),
-- event 38: Veridian technical
(55,38,49,'participant'),
-- event 39: Threshold technical interview
(56,39,49,'participant'),
(57,39,57,'interviewer'),
-- event 40: Evan accepts offer
(58,40,49,'participant'),
(59,40,56,'offerer'),
-- event 41: Megan lease
(60,41,50,'participant'),
-- event 42: Megan moves in
(61,42,50,'moving_in'),
(62,42,52,'helper'),
(63,42,54,'helper'),
(64,42,49,'witness_neighbor'),
-- event 43: Evan first day
(65,43,49,'participant'),
(66,43,56,'employer'),
(67,43,57,'manager'),
(68,43,58,'colleague'),
(69,43,59,'colleague'),
(70,43,60,'colleague'),
(71,43,61,'colleague'),
(72,43,62,'colleague'),
-- event 44: Eric/Anna wedding
(73,44,59,'groom'),
(74,44,63,'bride');


-- =============================================================================
-- RELATIONSHIPS  (38 rows: 23 existing + 15 new)
-- =============================================================================
INSERT INTO relationships
    (id,character_a_id,character_b_id,relationship_type,relationship_subtype,
     start_date,end_date,current_status,direction,notes,source_file)
VALUES
-- existing
(1,1,2,'romantic',NULL,'2025-09-06',NULL,'boyfriend_girlfriend',NULL,
 'Kate and Paul became official boyfriend/girlfriend December 28, 2025. First met September 6, 2025. First kiss September 26. First "I love you" December 27, 2025.',NULL),
(2,3,10,'family','father_daughter',NULL,NULL,'active',NULL,
 'Dysfunctional relationship. Charles dismissive, controlling through money.',NULL),
(3,3,11,'family','mother_daughter',NULL,NULL,'active',NULL,
 'Dysfunctional. Victoria confides inappropriately, uses Emma as emotional support.',NULL),
(4,3,12,'family','siblings',NULL,NULL,'active',NULL,
 'Competitive but occasionally allied against parents.',NULL),
(5,4,14,'family','siblings',NULL,NULL,'active',NULL,
 'Two of three O''Brien brothers. Constant banter, deep loyalty.',NULL),
(6,4,16,'family','siblings',NULL,NULL,'active',NULL,
 'Patrick is middle brother, Sean is youngest.',NULL),
(7,8,40,'romantic_partner','married','2018-06-01',NULL,'active',NULL,
 'Strong partnership built on mutual respect and shared goals.',NULL),
(8,1,31,'professional','advisor_advisee','2022-09-06',NULL,'active',NULL,
 'Primary dissertation advisor. Demanding but supportive.',NULL),
(9,1,32,'professional','committee_member','2024-04-21',NULL,'active',NULL,
 'Committee member. Practical questions about implementation.',NULL),
(10,1,33,'professional','committee_member','2024-04-21',NULL,'active',NULL,
 'Committee member. Chemistry expertise.',NULL),
(11,1,34,'professional','committee_member','2024-04-21',NULL,'active',NULL,
 'Committee member. Statistics expertise.',NULL),
(12,1,35,'professional','committee_member','2024-04-21',NULL,'active',NULL,
 'External committee member.',NULL),
(13,1,36,'professional','lab_colleague','2022-09-01',NULL,'active',NULL,
 'Postdoc who trained Kate on equipment.',NULL),
(14,7,39,'ex_partner','ex_spouse','2016-10-01','2019-01-01','ended',NULL,
 'Met at wedding summer 2015. Divorced 2019.',NULL),
(15,6,28,'family','cousins',NULL,NULL,'active',NULL,
 'Closest cousin to Ashley - best friend level.',NULL),
(16,6,21,'family','cousins',NULL,NULL,'active',NULL,
 'Close cousin, similar age and personality.',NULL),
(17,6,23,'family','cousins',NULL,NULL,'active',NULL,
 'Close cousin, same age, similar values.',NULL),
(18,1,44,'family','mother_daughter','1993-03-15',NULL,'active',NULL,
 'Complex relationship. Linda loving but anxious and overwhelming. Kate loves her but finds her exhausting. Weekly Sunday phone calls maintained.',NULL),
(19,1,9,'family','siblings',NULL,NULL,'active',NULL,
 'Siblings with opposite personalities. Mike is sociable and easy, Kate is analytical and guarded. They love each other but don''t fully understand each other.',NULL),
(20,1,45,'friendship','best_friends','2022-09-01',NULL,'active',NULL,
 'Kate''s only close friend. Met in PhD program at Northwestern. Priya is warm and extroverted, balances Kate''s introversion. Priya understands Kate''s anxiety without judgment.',NULL),
(21,9,6,'romantic','engaged','2024-12-01',NULL,'active',NULL,
 'Engaged December 2024. Wedding planned June 2026. Live together in West Loop. Strong, supportive relationship.',NULL),
(22,45,46,'romantic','engaged','2024-12-15',NULL,'active',NULL,
 'Engaged December 15, 2024. Wedding planned June 2026. Live together in Evanston. Met through mutual friends in grad school.',NULL),
(23,2,7,'friendship','best_friends','2013-11-01',NULL,'active',NULL,
 'Paul''s closest male friend. Met in consulting in 2013. Marcus lived with Paul during his crisis in 2019. Monthly Blackhawks games tradition. Marcus credits Paul with saving his life.',NULL),
-- new
(24,49,50,'acquaintance','neighbor_emerging','2026-02-28',NULL,'active','bidirectional',
 'Met February 28, 2026 when Evan noticed move-in activity at 4612 N. Glenwood. Slow accumulation of courtyard encounters from March 2026 onward. Neither is looking for a relationship. Friendship forming before either recognizes it.',
 'scene-2026-02-28-saturday-evan-narrative.md'),
(25,49,56,'professional','employee_employer','2026-03-02',NULL,'active','directional',
 'Evan hired as Software Engineer. Offer Feb 24, start March 2. Vikram Desai conducted technical interview (Feb 23). $115K salary.',
 'scene-2026-02-24-tuesday-evan-offer-day-narrative.md'),
(26,1,56,'professional','consultant_contractor','2026-03-01',NULL,'active','directional',
 'Kate hired as part-time research scientist / data consultant. $55/hr. Offer accepted Feb 20. Starts March 1. Initial contact: Samir email Jan 22, Samir call Jan 24, Vikram meeting Feb 3, office visit Feb 9.',
 'kate-morrison-threshold-water-complete-timeline.md'),
(27,50,52,'family','father_daughter',NULL,NULL,'active','bidirectional',
 'Karl and Megan. Karl communicates through action not words. Karl on the floor making animal sounds with Nora is the softest thing about him.',
 'megan-lindqvist-complete-background.md'),
(28,50,53,'family','mother_daughter',NULL,NULL,'active','bidirectional',
 'Birgit and Megan. Birgit is the problem-solver. When Megan came home with six-month-old Nora and a dissolving marriage, Birgit''s response was operational: what does Megan need to function?',
 'megan-lindqvist-complete-background.md'),
(29,50,54,'family','siblings',NULL,NULL,'active','bidirectional',
 'Megan and Erik. Erik helped move Megan in Feb 28. Opinion of Ryan Callahan: "He''s a piece of shit and I hope his car breaks down in Indiana."',
 'megan-lindqvist-complete-background.md'),
(30,50,55,'ex_partner','ex_spouse','2022-01-01','2026-01-01','ended','directional',
 'Married ~2022, divorce finalized January 2026. Ryan moved out Aug 1, 2025. Megan filed September 2025. No contest. Minimum child support ($400/mo). No custody or visitation requested. Ryan functionally abandoned Nora.',
 'megan-lindqvist-complete-background.md'),
(31,50,51,'family','mother_daughter','2025-01-18',NULL,'active','bidirectional',
 'Megan is Nora''s mother and primary parent. Nora born January 18, 2025 at Swedish Hospital.',
 'megan-lindqvist-complete-background.md'),
(32,55,51,'family','father_daughter','2025-01-18',NULL,'estranged','directional',
 'Ryan Callahan is Nora''s biological father. Functionally absent since Aug 2025. Pays $400/mo child support intermittently. No contact, no visitation.',
 'megan-lindqvist-complete-background.md'),
(33,49,64,'friendship','close_friend','2017-01-01',NULL,'active','bidirectional',
 'Closest friend from SEAL Teams. Same squad. Kyle Dunning from North Carolina. Stay in touch via EVE Online (same corporation OSBL-V) — the shared context that keeps the friendship alive across distance.',
 'evan-mercer-complete-background.md'),
(34,56,57,'professional','co_founders','2020-10-01',NULL,'active','bidirectional',
 'Samir (CEO) and Vikram (CTO) co-founded Threshold Water October 2020. Samir: domain knowledge and problem. Vikram: engineering depth. Complementary skills, strong working relationship.',
 'threshold-water-snapshot-feb-2026.md'),
(35,59,63,'romantic','engaged','2026-01-01',NULL,'active','bidirectional',
 'Eric Tran and Anna Zielinska. Eric had the ring since December 2025. Proposed late January 2026. Courthouse wedding April 17, 2026.',
 'anna-eric-2026-complete-timeline.md'),
(36,52,53,'family','married','1980-03-01',NULL,'active','bidirectional',
 'Karl and Birgit married March 1980 at Ravenswood Covenant. Met 1977 at church building project. Over 40 years together. Same house, same church, same kitchen table chairs.',
 'karl-lindqvist-complete-background.md'),
(37,52,54,'family','father_son',NULL,NULL,'active','bidirectional',
 'Karl and Erik. Erik is louder and less restrained than Karl.',
 'megan-lindqvist-complete-background.md'),
(38,52,51,'family','grandfather_granddaughter','2025-01-18',NULL,'active','bidirectional',
 'Karl and Nora. The man who communicated in socket wrenches for forty years gets on the floor and makes animal sounds with a thirteen-month-old.',
 'karl-lindqvist-complete-background.md');


-- =============================================================================
-- POSSESSIONS  (19 rows: 13 existing + 6 new)
-- Corrections: id=12 name/description, id=13 description
-- =============================================================================
INSERT INTO possessions
    (id,owner_id,item_name,item_category,item_description,
     acquisition_date,acquisition_method,acquisition_from,
     location_id,storage_location,
     monetary_value,sentimental_value,significance_notes,is_current,source_file)
VALUES
-- existing Kate possessions (ids 1-11, unchanged)
(1,1,'Grandmother''s Necklace','jewelry',
 'Silver necklace inherited from Kate''s grandmother.',
 NULL,NULL,NULL,NULL,NULL,NULL,'high','Highly sentimental family heirloom.',1,NULL),
(2,1,'Hario gooseneck kettle',NULL,
 'Paired with Chemex for pour-over coffee ritual.',
 NULL,NULL,NULL,NULL,'Paul''s house (as of Jan 2026)',NULL,'medium',
 'Part of sacred morning coffee ritual. Precise water temperature.',1,NULL),
(3,1,'Baratza Encore grinder',NULL,
 'Burr coffee grinder for consistent grind.',
 NULL,NULL,NULL,NULL,'Paul''s house (as of Jan 2026)',NULL,'medium',
 'Grinds beans fresh each morning. Exact amount every time.',1,NULL),
(4,1,'Running medals collection',NULL,
 '9 race medals including one marathon. Proof of finishing things.',
 NULL,NULL,NULL,NULL,'Kate''s apartment bedroom wall',NULL,'high',
 'Only things on walls besides watershed map. Naperville Half (2014), Chicago Marathon (2016, 3:54:32, cried at finish), various 10Ks and halfs.',1,NULL),
(5,1,'Mike''s UIUC sweatshirt',NULL,
 'Navy blue, Fighting Illini, worn soft. Mike gave for 18th birthday. Small bleach stain, missing drawstring.',
 NULL,NULL,NULL,NULL,'Kate''s apartment bottom drawer',NULL,'high',
 'Wore constantly freshman year. Evidence Mike once paid attention. Can''t throw away.',1,NULL),
(6,1,'Nancy Drew collection',NULL,
 '28 books, yellowed pages. Ages 8-12. First fictional character Kate identified with.',
 NULL,NULL,NULL,NULL,'Mom''s house Naperville (closet)',NULL,'medium',
 'Some volumes falling apart. Can''t throw away despite not rereading.',1,NULL),
(7,1,'Harry Potter series',NULL,
 'All 7, original US editions. HP1 extremely worn (read 15+ times). Marginalia in pencil.',
 NULL,NULL,NULL,NULL,'Mom''s house Naperville (closet)',NULL,'medium',
 'Connection to period when she read for joy, not escape.',1,NULL),
(8,1,'Silent Spring book',NULL,
 'Rachel Carson. High school Environmental Science class (2009). Changed her life direction. Yellow highlighter throughout. Notes from 17-year-old Kate.',
 NULL,NULL,NULL,NULL,'Mom''s house Naperville (closet)',NULL,'high',
 'Reminder of why she chose environmental engineering path.',1,NULL),
(9,1,'Science fair trophies',NULL,
 'Three trophies from middle school. 2nd place (6th), 1st place (7th & 8th). Water quality focused.',
 NULL,NULL,NULL,NULL,'Mom''s house Naperville (childhood bedroom)',NULL,'medium',
 'Evidence 13-year-old Kate cared about water quality. Tarnished gold plastic. Too childish to display as adult, too meaningful to discard.',1,NULL),
(10,1,'MacBook Pro 2021',NULL,
 'Primary work laptop for dissertation writing.',
 NULL,NULL,NULL,NULL,'Kate''s apartment desk',NULL,'low',
 'With external monitor, wireless keyboard and mouse.',1,NULL),
(11,1,'Great Lakes watershed map',NULL,
 'Framed. Only wall art in apartment besides running medals.',
 NULL,NULL,NULL,NULL,'Kate''s apartment living room wall',NULL,'medium',
 'Evidence of professional identity in personal space.',1,NULL),
-- existing Paul possessions (ids 12-13, corrected)
(12,2,'Pinstripe','vehicle',  -- CORRECTED: was "Turing"
 '2014 Mini Cooper F56. Black body, white roof. Named "Pinstripe." Bought new. Second Mini he''s owned. Loves the handling.',  -- CORRECTED: was "2014 Mini Cooper S"
 NULL,'purchased',NULL,
 1,'Paul''s house',NULL,'high','Paul''s beloved Mini Cooper F56 named Pinstripe.',1,NULL),
(13,2,'Volvo XC40','vehicle',  -- name correct; description corrected
 '2019 Volvo XC40 R-Design. Blue body, black roof. Second car; used for winter and longer drives.',  -- CORRECTED: was "2021 Mini Cooper S - Blue (black roof)"
 NULL,'purchased',NULL,
 1,'Paul''s house',NULL,'medium','Paul''s second car for winter conditions and longer trips.',1,NULL),
-- new
(14,1,'2017 Mini Cooper S Hardtop "Clover"','vehicle',
 'British Racing Green, manual transmission. Named Clover. Bought January 2024 — wanted a reliable, fun car with a manual transmission that would not bore her on drives to field sites. Key fob battery dying in Sherman Ave parking lot was how she met Paul.',
 '2024-01-01','purchased',NULL,
 1,'Paul''s house garage/driveway, Skokie IL',
 NULL,'medium',
 'Meeting catalyst for Kate and Paul (both driving Mini Coopers, Sept 6 2025). Kate is Chicago Mini Motoring Club online member (lurker status). Follows Mini rules selectively.',
 1,'kate-morrison-mini-cooper-culture.md'),
(15,49,'2018 Toyota Tacoma (dark gray)','vehicle',
 'Dark gray, bought used Virginia Beach 2022 for $28,000 when Evan left the Teams. Drove to Chicago with everything he owned in the bed. Now in alley parking spot behind building ($75/month). Drives maybe twice/week — grocery runs, occasional gym, lakefront drive. Debating selling since the layoff (math: $22-24K, saves $215/mo in insurance + parking). Knows this. Has not listed it.',
 '2022-01-01','purchased','Virginia Beach dealership',
 16,'Alley parking spot behind 4612 N. Glenwood Ave ($75/mo)',
 23000.0,'high',
 'Last physical object connecting Evan to Virginia Beach and the Teams life. Selling feels like closing a door he is not sure he is ready to close. Evan knows this is not a rational financial position.',
 1,'evan-mercer-complete-background.md'),
(16,49,'Custom gaming PC','electronics',
 'Built from upgraded components of the original Portsmouth machine he built as a teenager. Better equipment than the furniture. Used primarily for EVE Online. Monitor, keyboard, and mouse on the IKEA desk.',
 NULL,'built',NULL,
 17,'Desk in living room, Apt 2R',
 NULL,'medium',
 'Direct line from the PC he built in a Portsmouth garage as a teenager. The progression from that machine to this one mirrors his entire life arc.',
 1,'evan-mercer-complete-background.md'),
(17,49,'Framed platoon photo','photograph',
 'Evan''s SEAL platoon photo taken before Deployment 2. 16 men in desert camo, squinting into the sun. On the desk in the apartment. He does not look at it often. He knows it''s there.',
 NULL,NULL,NULL,
 17,'Desk, Apt 2R',
 NULL,'high',
 'Only personal item visible in the apartment besides the pull-up bar. The platoon. The people. The mission.',
 1,'evan-mercer-complete-background.md'),
(18,50,'IKEA Friheten sleeper sofa (gray)','furniture',
 'Gray sleeper sofa from IKEA. 180 lbs in the box. Karl and Erik carried it up three flights on move-in day (Feb 28). Against the far wall of the living room.',
 '2026-02-01','purchased','IKEA',
 18,'Living room, Apt 3F',
 NULL,'low',
 'Part of Megan''s fresh-start furnishing. She left Ryan''s furniture behind. Everything new in the apartment is from Lindqvist house or IKEA.',
 1,'megan-lindqvist-complete-background.md'),
(19,50,'Black dress (Banana Republic)','clothing',
 'Knee-length, fitted, jersey fabric. Bought on sale before the pregnancy. Wore it to the divorce proceedings. Hangs in the back of the closet. She has not decided whether to keep it.',
 NULL,'purchased','Banana Republic',
 18,'Back of closet, Megan''s bedroom, Apt 3F',
 NULL,'high',
 'The one "exception" item in Megan''s wardrobe — everything else is functional, washable, comfortable. Last worn at divorce proceedings.',
 1,'megan-lindqvist-complete-background.md');


-- =============================================================================
-- SCHEDULES  (15 rows: 8 existing + 7 new)
-- Correction: id=6 location/start_time
-- =============================================================================
INSERT INTO schedules
    (id,character_id,schedule_type,schedule_name,days_of_week,
     start_time,end_time,duration_minutes,
     location_id,location_description,description,exceptions,
     effective_from,effective_until,is_current,source_file)
VALUES
-- existing
(1,2,'work','Mumbai Team Standup',
 '["Monday","Tuesday","Wednesday","Thursday","Friday"]',
 '07:00','09:00',NULL,NULL,'Home office',
 'Early morning Mumbai team standup calls — STARTS AT 7 AM, NOT 9 AM.',
 '["US holidays","personal time off"]',
 NULL,NULL,1,NULL),
(2,2,'work','Regular Work Hours',
 '["Monday","Tuesday","Wednesday","Thursday","Friday"]',
 '09:00','17:00',NULL,NULL,'Home office',
 'Regular work hours — meetings, management tasks, occasional coding (5% coding, 95% meetings).',
 '["US holidays","personal time off"]',
 NULL,NULL,1,NULL),
(3,2,'personal','Morning Routine',
 '["Monday","Tuesday","Wednesday","Thursday","Friday"]',
 '05:40','06:30',NULL,NULL,'Home',
 'Morning routine — wake, breakfast, coffee.',
 NULL,NULL,NULL,1,NULL),
(4,1,'weekly_commitment','Lab meeting',
 '["thursday"]',
 '14:00','16:00',NULL,NULL,'Tech Building, Northwestern',
 'Data presentations, troubleshooting, paper planning. Kate prepares carefully. Presents every 3-4 weeks.',
 NULL,NULL,NULL,1,NULL),
(5,1,'weekly_commitment','Thursday coffee social',
 '["thursday"]',
 '15:00','16:00',NULL,NULL,'Chen Lab kitchen',
 'Informal gathering. Patricia brings good coffee. Kate attends ~80% of time, stays 30-40 minutes.',
 NULL,NULL,NULL,1,NULL),
-- id=6 corrected: Skokie location, 06:20 start
(6,1,'exercise','Morning Run',
 '["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"]',
 '06:20','07:00',NULL,NULL,  -- CORRECTED from 06:00
 'Skokie neighborhood streets from Paul''s house (moved from Evanston lakefront Jan 2026). Still learning routes. Returns before Paul''s 7 AM call.',  -- CORRECTED
 'Kate runs 4-5 miles most mornings. Outdoor running strongly preferred. Treadmill only if below 15°F. Running is emotional regulation and processing time.',
 '["severe weather","illness","travel"]',
 '2026-01-01',NULL,1,NULL),
(7,1,'daily_routine','Morning Coffee Ritual',
 '["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"]',
 '06:45','07:15',NULL,NULL,'Home (or Paul''s house)',
 'Sacred morning ritual. Chemex pour-over, precisely measured, specific process. Only time Kate allows herself precision and attention to a non-work activity.',
 NULL,NULL,NULL,1,NULL),
(8,1,'weekly_commitment','Sunday call with Mom',
 '["Sunday"]',
 '14:00','14:30',NULL,NULL,'Phone',
 'Weekly phone call with Linda. Kate maintains this obligation despite finding calls draining. Linda needs connection more than Kate does. Calls average 20-30 minutes.',
 '["travel","major events"]',
 NULL,NULL,1,NULL),
-- new
(9,49,'exercise','Morning Run',
 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday',
 '06:30','07:30',NULL,NULL,
 'Ravenswood streets or Chicago Lakefront Path (North Ave to Foster area)',
 'Runs 3-5 miles most mornings. Left knee (reconstructed ACL/meniscus) requires brace. Gait slightly asymmetric — only he and his PT notice. Running is maintenance, not hobby. Supplements with bodyweight circuits in apartment (pull-ups, push-ups, core, air squats).',
 '["extreme cold","knee flare-up","late-night EVE Online session"]',
 NULL,NULL,1,'evan-mercer-complete-background.md'),
(10,49,'work','Threshold Water — Software Engineer',
 'Monday,Tuesday,Wednesday,Thursday,Friday',
 '09:00','17:00',NULL,
 19,'Threshold Water Inc., 220 N Green Street, Chicago IL 60607',
 'Full-time software engineer. Hybrid — some days in office, some remote. Backend-heavy: Python/FastAPI, PostgreSQL/PostGIS, AWS infrastructure, telemetry ingestion pipelines. Incident response is primary strength.',
 '["US holidays","PTO"]',
 '2026-03-02',NULL,1,'evan-mercer-complete-background.md'),
(11,49,'leisure','EVE Online',
 'Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday',
 '20:00','23:30',NULL,
 17,'Apartment (gaming PC)',
 'Plays EVE Online most evenings, variable length. Corporation: OSBL-V. Close friend Kyle Dunning (Virginia Beach) in same corp. Primary activities: PLEX sales and wormhole site-running. Omega subscription paid separately. Wormhole systems cannot be bookmarked. EVE is both hobby and primary social connection.',
 '["early bedtime","social obligation"]',
 NULL,NULL,1,'evan-mercer-complete-background.md'),
(12,50,'work','Day Shift — Swedish Hospital Oncology',
 'variable (3 day shifts/week avg)',
 '07:00','19:00',720,
 20,'Swedish Hospital, 5145 N. California Ave, Chicago IL',
 '12-hour day shifts (7A-7P). Chemotherapy administration, port access, infusion protocol management, antiemetic regimens, neutropenic precautions, pain management, lab value monitoring. Drops Nora at parents'' house (4848 N. Hermitage) before shift.',
 '["scheduled days off","sick leave"]',
 NULL,NULL,1,'megan-lindqvist-complete-background.md'),
(13,50,'work','Night Shift — Swedish Hospital Oncology',
 'variable (roughly 1 night shift/week)',
 '19:00','07:00',720,
 20,'Swedish Hospital, 5145 N. California Ave, Chicago IL',
 '12-hour night shifts (7P-7A). Drops Nora at Lindqvist house (4848 N. Hermitage) at 6:00 PM. Birgit does Nora''s bedtime. Nora sleeps at grandparents''. Megan picks Nora up next morning after sleeping a few hours at apartment.',
 '["scheduled days off"]',
 NULL,NULL,1,'megan-lindqvist-complete-background.md'),
(14,50,'daily_routine','Nora Drop-off (Day Shift)',
 'variable (day shift days)',
 '06:00','06:30',NULL,
 21,'Karl & Birgit''s house, 4848 N. Hermitage Ave',
 'Drops Nora at Lindqvist house before day shift. Six blocks from building.',
 NULL,NULL,NULL,1,'megan-lindqvist-complete-background.md'),
(15,1,'work','Threshold Water Consulting — Part-Time',
 'Monday,Tuesday,Wednesday,Thursday,Friday',
 '09:00','17:00',NULL,
 19,'Remote (Paul''s house, Skokie) + occasional in-person at 220 N Green St',
 'Part-time research scientist / data consultant. March-April: 10-15 hrs/week, data audit and model setup. May: 20-25 hrs/week as results emerge (88% accuracy target). Rate: $55/hr. Manages and mentors Daniel Wu (junior data scientist).',
 '["dissertation deadlines","Northwestern lab meetings","Mike''s wedding week Jun 7-14"]',
 '2026-03-01',NULL,1,'kate-morrison-threshold-water-complete-timeline.md');


-- =============================================================================
-- CHARACTER NEGATIVES  (22 rows: 12 existing + 10 new)
-- Correction: id=3 explanation (celiac → non-celiac)
-- =============================================================================
INSERT INTO character_negatives
    (id,character_id,negative_category,negative_behavior,
     strength,explanation,exception_conditions,source_file)
VALUES
-- existing
(1,1,'exercise','Does NOT go to gyms',
 'absolute','Kate strongly prefers outdoor running and never uses gym facilities.',NULL,NULL),
(2,1,'exercise','Does NOT run on treadmills',
 'absolute','Kate hates treadmills and finds them unbearable.',
 '["will use treadmill ONLY if temperature is below 15°F (-9°C)"]',NULL),
-- id=3 corrected: non-celiac gluten sensitivity, NOT celiac disease
(3,1,'food','Does NOT eat gluten',
 'absolute',
 'Kate has non-celiac gluten sensitivity (NOT celiac disease). Avoids all gluten; reacts with GI distress and fatigue. Does not label ordinary home food as "gluten-free" — it is just food.',  -- CORRECTED
 NULL,'kate-morrison-food-eating-behavior.md'),
(4,1,'food','Does NOT drink regular coffee after 2 PM',
 'strong','Kate avoids caffeine in afternoon to protect sleep quality.',
 '["may have decaf after 2 PM","exceptions for special occasions"]',NULL),
(5,1,'exercise','Does NOT do yoga',
 'preference','Kate tried yoga but finds it boring and prefers running.',NULL,NULL),
(6,1,'social','Does NOT attend student mixers at conferences',
 'strong','Skipped AGU student mixer (too anxiety-inducing). Too overwhelming, too many people.',NULL,NULL),
(7,1,'social','Does NOT stay at networking events longer than 45-60 minutes',
 'strong','Maximum capacity. Leaves after reasonable effort. Did minimum necessary, not maximum beneficial.',
 'If required for specific professional reason',NULL),
(8,1,'social','Does NOT attend conference banquets or social dinners',
 'strong','Skipped SETAC conference banquet, EPA mixer. Patricia frustrated but Kate "just can''t."',
 'Required for committee or advisor',NULL),
(9,1,'social','Does NOT pursue connections made at conferences',
 'preference','Exchanged cards with 8-10 people, followed up with 4-5 briefly. Pattern of letting connections drift.',
 'If professional collaboration clearly valuable',NULL),
(10,1,'social','Does NOT use dating apps',
 'strong','Kate finds dating apps overwhelming and anxiety-inducing. Met Paul organically. Prefers natural connections despite limiting opportunities.',NULL,NULL),
(11,1,'social','Does NOT host social gatherings at her apartment',
 'strong','Kate''s apartment is her retreat, not a social space. Has never hosted a party or dinner party. Priya is only friend who has spent significant time there.',NULL,NULL),
(12,2,'food','Does NOT eat gluten',
 'absolute','Paul has gluten intolerance and must avoid all gluten.',NULL,NULL),
-- new: Evan
(13,49,'social','Does NOT discuss classified operational details from deployments',
 'absolute',
 'Standard SEAL/SOF practice. Not evasion — the work is classified and Evan has decided certain experiences are not for civilian consumption. Will say "previous job" and not elaborate.',
 NULL,'evan-mercer-complete-background.md'),
(14,49,'social','Does NOT initiate social contact without shared context or proximity',
 'strong',
 'Evan waits for shared context (neighbor encounter, workplace, shared activity) rather than reaching out proactively. Teams relationships were sustained by proximity and shared mission; without those, maintenance falls to the individual.',
 '["Kyle Dunning (EVE Online provides ongoing shared context)","workplace colleagues once established"]',
 'evan-mercer-complete-background.md'),
(15,49,'social','Does NOT ask for help proactively',
 'strong',
 'Core trait from Portsmouth stoicism and SEAL culture. Perform, don''t process. Personal life is your problem. Will accept help when directly offered; will not request it.',
 '["extreme necessity","workplace (appropriate to ask there)"]',
 'evan-mercer-complete-background.md'),
(16,49,'social','Does NOT maintain long-distance friendships without active shared context',
 'strong',
 'Platoon relationships dissolved without proximity and shared mission. Knows names, wives, kids of former teammates but in touch with almost none of them. Kyle Dunning is the one exception (EVE Online provides daily shared context).',
 '["Kyle Dunning"]','evan-mercer-complete-background.md'),
(17,49,'exercise','Does NOT train for aesthetics (heavy barbell / bodybuilding)',
 'preference',
 'SEAL Teams trained endurance and mental durability, not aesthetics. Occasionally uses gym for functional work (kettlebells, rowing, sandbag carries) but heavy barbell sessions are not his thing. "The guys who showed up to BUD/S jacked and slow were the guys who rang the bell."',
 '["functional gym work: kettlebells, rowing, sandbag carries"]',
 'evan-mercer-complete-background.md'),
(18,49,'behavior','Does NOT express emotion or vulnerability without significant established trust',
 'strong',
 'Portsmouth stoicism + SEAL Teams perform-don''t-process culture. Aisha: "There''s nothing hidden — there''s just nothing offered." Evan doesn''t share. He doesn''t let people in. He doesn''t know where the door is.',
 '["Kyle Dunning (partial exception)","built over significant time with right person"]',
 'evan-mercer-complete-background.md'),
-- new: Megan
(19,50,'social','Does NOT discuss Ryan Callahan with new people',
 'strong',
 'Megan does not say "He left his daughter" out loud because saying it makes it more real. New people get: divorced, single mother. Not the specifics.',
 '["close friends like Dana Jefferson","her parents and Erik"]',
 'megan-lindqvist-complete-background.md'),
(20,50,'social','Does NOT have significant discretionary social time',
 'strong',
 'Three 12-hour shifts per week plus Nora on days off leaves almost no free time. Hard hours (7:30 PM after Nora''s bedtime to 10 PM) are the only real solitude. Social plans require childcare coordination with Karl and Birgit.',
 '["days off when Karl/Birgit take Nora for extended stretch"]',
 'megan-lindqvist-complete-background.md'),
(21,50,'exercise','Does NOT exercise recreationally',
 'preference',
 'No time and no need. Twelve-hour shifts mean Megan is on her feet, lifting patients, moving fast for 12 hours. Her body is maintained by work rather than intention. Running, gym, yoga are not part of her life.',
 NULL,'megan-lindqvist-complete-background.md'),
(22,50,'behavior','Does NOT struggle to ask for help — will ask when necessary',
 'preference',
 'KEY behavioral difference from Evan. Megan can ask for help. She asked her parents. Her lawyer. Her charge nurse for a schedule adjustment. Asking for help is triage, not weakness: assess what you can carry and delegate what you cannot.',
 NULL,'megan-lindqvist-complete-background.md');


-- =============================================================================
-- EDUCATION  (20 rows: 8 existing + 12 new)
-- =============================================================================
INSERT INTO education
    (id,character_id,institution,degree_type,field_of_study,
     start_year,end_year,is_completed,is_current,
     honors,thesis_title,advisor,notes,source_file)
VALUES
-- existing
(1,8,'University of Illinois Urbana-Champaign','B.A.','Advertising',
 2012,2016,1,0,
 'Dean''s List, cum laude',NULL,NULL,
 'Minor in Psychology. Ad Club vice president senior year. Study abroad London Spring 2015. Met Steve senior year.',NULL),
(2,8,'Google Ads',NULL,'Google Ads certification',
 NULL,NULL,1,0,NULL,NULL,NULL,'Industry certification for advertising work.',NULL),
(3,8,'Facebook Blueprint',NULL,'Facebook Blueprint certification',
 NULL,NULL,1,0,NULL,NULL,NULL,'Industry certification for advertising work.',NULL),
(4,40,'Northwestern University','MBA','Business',
 2015,2017,1,0,
 'Kellogg School',NULL,NULL,
 'Met Alice while visiting UIUC friends January 2016.',NULL),
(5,21,'Unknown','BSN','Nursing',
 NULL,NULL,1,0,NULL,NULL,NULL,'Works at Northwestern Memorial Hospital.',NULL),
(6,24,'Loyola University Chicago','M.D.','Medicine',
 2023,2027,1,0,
 'Stritch School of Medicine',NULL,NULL,
 'Year 3 medical student. Sean and Maria''s son.',NULL),
(7,30,'University of Chicago','MSW','Social Work',
 2022,2024,1,0,NULL,NULL,NULL,'Marie and James''s daughter. Starting social work career.',NULL),
(8,29,'Unknown','B.S.','Computer Science',
 NULL,NULL,1,0,NULL,NULL,NULL,'Software engineer. Marie and James''s son. Engaged to Jennifer.',NULL),
-- new: Kate
(9,1,'University of Illinois Urbana-Champaign','B.S.','Environmental Engineering',
 2011,2015,1,0,
 'Dean''s List, multiple semesters',NULL,NULL,
 'Undergrad research on water quality sparked interest in PFAS. Senior thesis on Great Lakes tributary sampling.',
 'kate-morrison-character-background.md'),
(10,1,'AECOM Technical Services',NULL,'Environmental Consulting (Industry)',
 2015,2018,1,0,NULL,NULL,NULL,
 'Three years as environmental consultant between undergrad and PhD. Field work at industrial sites and municipal utilities. Left to pursue research.',
 'kate-morrison-character-background.md'),
(11,1,'Northwestern University','Ph.D.','Environmental Engineering (Civil & Environmental)',
 2022,NULL,0,1,
 'NSF Graduate Research Fellow (GRFP, Years 1-3)',
 'Predictive Modeling of PFAS and Microplastic Contamination in Great Lakes Drinking Water Systems',
 'Dr. Patricia Chen',
 'ABD (comprehensive exam April 21, 2024). Proposal defense October 15, 2025. Target defense Fall 2027. WRF grant awarded ~Feb 15, 2026 ($47,500).',
 'kate-morrison-northwestern-phd-comprehensive.md'),
-- new: Evan
(12,49,'Old Dominion University (ODU)','B.S.','Computer Science',
 2022,2024,1,0,NULL,NULL,'Dr. Raymond Osei (systems programming)',
 'Enrolled as junior with 45 transfer credits from active-duty ODU classes. Backend/systems focus per advisor. Booz Allen internship summer 2023 (Navy logistics platform). Booz Allen offered full-time; Evan declined, relocated to Chicago.',
 'evan-mercer-complete-background.md'),
-- new: Megan
(13,50,'Loyola University Chicago','B.S.N.','Nursing',
 2020,2024,1,0,NULL,NULL,NULL,
 'Met Ryan Callahan sophomore year (2021). Transferred to oncology unit November 2024 after charge nurse recommendation.',
 'megan-lindqvist-complete-background.md'),
-- new: Samir
(14,56,'University of Michigan','B.S.','Environmental Engineering',
 2007,2011,1,0,NULL,NULL,NULL,
 'Grew up in Ann Arbor.',
 'samir-rajesh-patel-complete-background.md'),
(15,56,'Massachusetts Institute of Technology (MIT)','Ph.D.','Environmental Engineering',
 2011,2017,1,0,NULL,
 'Predictive modeling of water distribution network contamination risk',
 NULL,
 'Thanksgiving 2015 Dearborn visit was watershed moment — saw three kids with elevated lead levels. Left academia to found Threshold Water October 2020.',
 'samir-rajesh-patel-complete-background.md'),
-- new: Vikram
(16,57,'University of Illinois Urbana-Champaign','B.S.','Computer Science',
 2002,2006,1,0,NULL,NULL,NULL,
 'Born Mumbai, immigrated age 3. Full financial aid.',
 'vikram-desai-complete-background.md'),
(17,57,'Carnegie Mellon University','M.S.','Software Engineering',
 2006,2008,1,0,NULL,NULL,NULL,
 'Then 14 years industry experience before co-founding Threshold Water.',
 'vikram-desai-complete-background.md'),
-- new: Eric Tran
(18,59,'Unknown','B.S.','Computer Science or related',
 NULL,NULL,1,0,NULL,NULL,NULL,
 'Full-stack engineer. First full year at Threshold Water in 2026.',
 'anna-eric-2026-complete-timeline.md'),
-- new: Anna Zielinska
(19,63,'Truman College (City Colleges of Chicago)',NULL,'Dental Hygiene Prerequisites',
 2024,2026,0,1,NULL,NULL,NULL,
 'Completed: Bio 121 (A), Chemistry (B+), A&P I (A-), Speech 101 (A). Applied Jan 15, 2026 to Malcolm X College. Accepted ~May 1, 2026.',
 'anna-eric-2026-complete-timeline.md'),
(20,63,'Malcolm X College (City Colleges of Chicago)','A.A.S.','Dental Hygiene',
 2026,2028,0,1,NULL,NULL,NULL,
 'Starts June 3, 2026. Six semesters (~2 years). Will continue cafe shifts on Saturdays.',
 'anna-eric-2026-complete-timeline.md');


-- =============================================================================
-- INGESTION METADATA + LAST RUN STATE
-- =============================================================================
INSERT INTO last_run_state (id, last_successful_run) VALUES (1, datetime('now'));

INSERT INTO ingestion_metadata
    (run_timestamp,mode,source_directory,
     files_processed,tags_processed,records_inserted,records_updated,records_deleted,
     errors,duration_seconds)
VALUES
(datetime('now'),'full_reload','canonical_facts_full_reload.sql',
 0,0,0,0,0,0,0);


COMMIT;
PRAGMA foreign_keys = ON;

-- =============================================================================
-- VERIFICATION
-- =============================================================================
SELECT 'characters'          AS tbl, COUNT(*) AS n FROM characters         UNION ALL
SELECT 'locations',                   COUNT(*)      FROM locations          UNION ALL
SELECT 'location_rooms',              COUNT(*)      FROM location_rooms     UNION ALL
SELECT 'timeline_events',             COUNT(*)      FROM timeline_events    UNION ALL
SELECT 'event_participants',          COUNT(*)      FROM event_participants UNION ALL
SELECT 'relationships',               COUNT(*)      FROM relationships      UNION ALL
SELECT 'possessions',                 COUNT(*)      FROM possessions        UNION ALL
SELECT 'schedules',                   COUNT(*)      FROM schedules          UNION ALL
SELECT 'character_negatives',         COUNT(*)      FROM character_negatives UNION ALL
SELECT 'education',                   COUNT(*)      FROM education;
